### ISSUE TITLE
Whats this about?

### ISSUE THREAD

**Issue by c1bles** [Hi-doki/audifyfix#1]
ik it's spotify related but nothing else

**Comment by Hi-doki** [comment]
This was just a small college project I wanted to do, it basically worked as an "alternative" Spotify web client, can't work on it anymore due to Spotify ruining basically all of the features: https://community.spotify.com/t5/Spotify-for-Developers/Why-did-Spotify-deprecate-basically-half-of-the-webAPI-endpoints/m-p/6557368#M16060

**Comment by c1bles** [comment]
> This was just a small college project I wanted to do, it basically worked as an "alternative" Spotify web client, can't work on it anymore due to Spotify ruining basically all of the features: https://community.spotify.com/t5/Spotify-for-Developers/Why-did-Spotify-deprecate-basically-half-of-the-webAPI-endpoints/m-p/6557368#M16060

ohh, looked kinda cool tho...

**Comment by Hi-doki** [comment]
> > This was just a small college project I wanted to do, it basically worked as an "alternative" Spotify web client, can't work on it anymore due to Spotify ruining basically all of the features: https://community.spotify.com/t5/Spotify-for-Developers/Why-did-Spotify-deprecate-basically-half-of-the-webAPI-endpoints/m-p/6557368#M16060
> 
> ohh, looked kinda cool tho...

yeah I tried to put a lot of effort on the design etc, kinda sad spotify deprecated basically all of it. Spotify support did they they will try to work on a replacement for developers but I'm not sure if they were being truthful or not
